name: Build and Publish Container Image
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: checkout files in repo
      uses: actions/checkout@main

    - name: update jupyter dependencies with repo2docker
      uses: jupyterhub/repo2docker-action@6a93d1bf173f32cfd859130d5851aa8a7aad07cd  # master as of 2020-10-20
      with:
        # Proactively build on mybinder.org for faster startup.
        MYBINDERORG_TAG: {{ '${{ github.event.ref }}' }}
        # Also push built image to DockerHub for use by our JupyterHub deployments.
        DOCKER_USERNAME: nsls2damaservice
        DOCKER_PASSWORD: {{ '${{ secrets.DOCKERHUB_ACCESS_TOKEN }}' }} 
        IMAGE_NAME: nsls2/{{ cookiecutter.repo_name }}
